# Generated by Django 2.2.6 on 2019-10-22 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('description', models.CharField(max_length=300, verbose_name='Descrição')),
                ('latitude', models.CharField(max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=100, null=True, verbose_name='Longitude')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído')], default='P', max_length=1, verbose_name='Status')),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='towers', to='client.Client', verbose_name='Cliente')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='towers', to='company.Company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Torre',
                'verbose_name_plural': 'Torres',
                'db_table': 'tower',
            },
        ),
    ]
