# Generated by Django 2.2.6 on 2019-11-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_is_active'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrotarization',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='users', to='company.Company', verbose_name='Empresa'),
        ),
    ]
