# Generated by Django 2.2.6 on 2019-10-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_company_is_active'),
        ('localization', '0003_localization_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Descrição')),
                ('origin_latitude', models.CharField(max_length=100, null=True, verbose_name='Origen Latitude')),
                ('origin_longitude', models.CharField(max_length=100, null=True, verbose_name='Origen Longitude')),
                ('origin_address', models.CharField(max_length=300, null=True, verbose_name='Origen Endereço')),
                ('destiny_latitude', models.CharField(max_length=100, null=True, verbose_name='Destino Latitude')),
                ('destiny_longitude', models.CharField(max_length=100, null=True, verbose_name='Destino Longitude')),
                ('destiny_address', models.CharField(max_length=300, null=True, verbose_name='Destino Endereço')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scriptings', to='company.Company', verbose_name='Empresa')),
                ('localizations', models.ManyToManyField(related_name='scripting', to='localization.Localization', verbose_name='localization')),
            ],
            options={
                'verbose_name': 'Roteirização',
                'verbose_name_plural': 'Roteirizações',
                'db_table': 'scripting',
            },
        ),
    ]
