# Generated by Django 2.2.6 on 2019-10-28 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripting', '0002_scripting_date_registred'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripting',
            name='date_final',
            field=models.DateField(default=datetime.date.today, verbose_name='Fim'),
        ),
        migrations.AddField(
            model_name='scripting',
            name='date_initial',
            field=models.DateField(default=datetime.date.today, verbose_name='Início'),
        ),
    ]
