# Generated by Django 2.2.6 on 2019-10-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripting', '0004_auto_20191028_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripting',
            name='localizations',
            field=models.ManyToManyField(null=True, related_name='scripting', to='localization.Localization', verbose_name='localization'),
        ),
    ]
