# Generated by Django 2.2.6 on 2019-11-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripting', '0007_auto_20191101_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripting',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('I', 'Em andamento'), ('C', 'Concluído')], default='P', max_length=1, verbose_name='Situação'),
        ),
    ]
