# Generated by Django 2.2.6 on 2019-11-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20191101_1937'),
        ('scripting', '0009_auto_20191104_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripting',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='scripting', to='employee.Employee', verbose_name='employee'),
        ),
    ]
