# Generated by Django 2.2.6 on 2019-10-26 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_company_is_active'),
        ('client', '0002_client_date_registred'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('description', models.CharField(max_length=300, verbose_name='Descrição')),
                ('latitude', models.CharField(max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=100, null=True, verbose_name='Longitude')),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='client.Client', verbose_name='Cliente')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='company.Company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'db_table': 'localization',
            },
        ),
    ]
