# Generated by Django 2.2.6 on 2019-10-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localization',
            name='address',
            field=models.CharField(max_length=300, null=True, verbose_name='Endereço'),
        ),
    ]
