# Generated by Django 2.2.6 on 2019-11-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0004_auto_20191028_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localization',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='client.Client', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localization',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='company.Company', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
